name: Calculate MD5 for the whole Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Calculate MD5
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./AutoCalcMD5.exe
      shell: bash
    
    - name: action-push
      uses: ludeeus/action-push