name: Calculate MD5 for the whole Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Calculate MD5
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./AutoCalcMD5.exe
      shell: bash
    
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: # optional, default is 
        # Destination branch to push changes
        branch: main
        # Determines if force push is used
        force: # optional
        # Determines if --tags is used
        tags: # optional
        # Directory to change to before pushing.
        directory: # optional, default is .