name: Update the Helper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download LXLDevHelperFile
      uses: carlosperate/download-file-action@v1.0.3
      with:
       file-url: "https://github.com/LiteLDev-LXL/LXLDevHelper-Library/raw/master/Library.zip"
       file-name: "Helper/Files/Library.zip"

    - name: Add & Commit
      uses: stefanzweifel/git-auto-commit-action@v4
